const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const pages = fs.readFileSync(path.join(root, "server", "pages.js"), "utf8");
const runScript = fs.readFileSync(path.join(root, "public", "agent-run.js"), "utf8");
const siteTheme = fs.readFileSync(path.join(root, "public", "local-site.css"), "utf8");

assert.match(pages, /id="run-feed-search" type="search"/);
assert.match(pages, /id="run-feed-export"[^>]+title="Export every move and its reasoning as JSON"/);
assert.match(pages, /id="run-feed-export-txt"[^>]+title="Export every move and its reasoning as plain text"/);
assert.equal((pages.match(/\$\{movesSection\}/g) || []).length, 2);
assert.equal((pages.match(/\$\{notesSection\}/g) || []).length, 1);
assert.ok(pages.indexOf("${mazeSections}") < pages.indexOf("${notesSection}"));
assert.ok(pages.indexOf("${notesSection}") < pages.indexOf("<h2>Runner log</h2>"));
assert.match(pages, /id="run-notes-input"[^>]+maxlength="50000"/);
assert.match(pages, /id="run-notes-save"/);
assert.match(pages, /class="run-notes__icon"/);
assert.match(pages, /id="run-notes-count">0 \/ 50,000/);
assert.doesNotMatch(pages, /id="run-summarize"|id="run-review-result"|Post-run analyst/);
assert.match(runScript, /function feedSearchTerms\(query\)/);
assert.match(runScript, /return terms\.every\(\(term\) => text\.includes\(term\)\)/);
assert.match(runScript, /function formatReasoning\(reasoning, terms\)/);
assert.match(runScript, /<mark>\$\{escapeText\(part\)\}<\/mark>/);
assert.match(runScript, /export_scope: "all_moves"/);
assert.match(runScript, /new Blob\(\[.*JSON\.stringify\(payload, null, 2\)/s);
assert.match(runScript, /reasoning: state\.reasoning\.get\(turn\) \|\| null/);
assert.match(runScript, /function feedTextExport\(payload\)/);
assert.match(runScript, /Maze Bench Agent Reasoning Log/);
assert.match(runScript, /-reasoning\.txt/);
assert.match(runScript, /feedTextExportButton\?\.addEventListener\("click", exportFeedText\)/);
assert.match(runScript, /function saveRunNotes\(\)/);
assert.match(runScript, /\/api\/agent\/runs\/\$\{encodeURIComponent\(runId\)\}\/notes/);
assert.match(runScript, /notesInput\?\.addEventListener\("input"/);
assert.match(runScript, /notesStatus\.dataset\.state = status/);
assert.match(runScript, /notesInput\.value\.length\.toLocaleString\(\)/);
assert.doesNotMatch(runScript, /renderRunReview|openReviewDialog|run-summarize/);
assert.match(runScript, /data-feed-expand=/);
assert.match(runScript, /function isMultiAgentRun\(\)/);
assert.match(runScript, /Invalid: \$\{invalidReason\}/);
assert.match(runScript, /Run failed — \$\{rolloutError\}/);
assert.match(runScript, /const agentBadge = multiAgentRun && activeAgents/);
assert.match(runScript, /<span class="agent-feed__num"[^>]*>\$\{escapeText\(num\)\}<\/span>\s*<strong class="agent-feed__action">[\s\S]*?<\/strong>\s*<button type="button" class="agent-feed__jump" data-jump-turn="\$\{escapeText\(num\)\}">Jump to Action \$\{escapeText\(num\)\}<\/button>/);
assert.match(siteTheme, /\.run-feed-toolbar \{/);
assert.match(siteTheme, /\.agent-feed__jump \{/);
assert.match(siteTheme, /\.agent-feed__reasoning\.is-collapsible:not\(\.is-expanded\) p \{/);
assert.match(siteTheme, /\.agent-feed mark \{/);
assert.match(siteTheme, /\.agent-log \{[\s\S]*?overflow-anchor: none/);
assert.match(siteTheme, /\.run-notes__input/);
assert.match(siteTheme, /\.run-notes__status\[data-state="dirty"\]/);
assert.match(siteTheme, /\.run-notes__save/);
assert.doesNotMatch(siteTheme, /box-shadow: inset 3px 0 0/);

console.log("agent-run-feed-source: OK — move logs are searchable, exportable, and clean in single-agent mode.");
